import { useEffect, useRef, useState } from 'react'
import { apiFetch } from '../../utils/api'
import { BrandLogo } from './BrandLogo'

/**
 * RaulClippy — bottom-right floating mascot (Word-Clippy vibe). Shows short,
 * witty one-liner tips generated by Raul from the latest Raul-rec input.
 *
 * Effects:
 *   - Letter-by-letter typewriter as each tip writes itself out
 *   - 5-second pause after a tip is fully typed
 *   - Then auto-cycles to the next tip with the typewriter again
 *   - At least 12 tips per cycle (server-side AI generates 12)
 *
 * Source of tips: GET /api/ai/clippy-tips (cached server-side by month;
 * refreshed as side-effect of POST /api/ai/recommendations, no extra OpenAI
 * call when the mascot mounts).
 *
 * Dismiss: × button silences mascot for 7 days (localStorage timestamp).
 * After that it self-restores. Self-hides entirely if no cached tips exist.
 */

const STORAGE_KEY = 'nu_clippy_dismissed_until'
const DISMISS_DURATION_MS = 7 * 24 * 60 * 60 * 1000 // 7 days
/** ms per character while the tip is being typed out. */
const TYPE_INTERVAL_MS = 35
/** Pause once the tip is fully typed, before cycling to the next. */
const READ_PAUSE_MS = 5_000

interface ClippyData {
  period: string | null
  tips: string[]
}

export function RaulClippy() {
  const [dismissed, setDismissed] = useState<boolean>(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY)
      if (!raw) return false
      const until = parseInt(raw, 10)
      return Number.isFinite(until) && Date.now() < until
    } catch {
      return false
    }
  })
  const [data, setData] = useState<ClippyData | null>(null)
  const [loading, setLoading] = useState(true)
  const [idx, setIdx] = useState(0)
  const [typed, setTyped] = useState('') // currently visible text
  const typingRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const pauseRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  // Initial fetch — server returns latest cached tips (any month).
  useEffect(() => {
    if (dismissed) return
    let alive = true
    apiFetch<ClippyData>('/api/ai/clippy-tips').then((res) => {
      if (!alive) return
      setData(res.ok ? res.data : { period: null, tips: [] })
      setLoading(false)
    })
    return () => {
      alive = false
    }
  }, [dismissed])

  const tips = data?.tips ?? []

  // Typewriter cycle: animate one character at a time, pause when done, move on
  useEffect(() => {
    if (tips.length === 0) return
    // Clean up any in-flight timers when we re-enter the effect
    if (typingRef.current) clearInterval(typingRef.current)
    if (pauseRef.current) clearTimeout(pauseRef.current)

    const fullText = tips[idx % tips.length] ?? ''
    setTyped('')
    let i = 0

    typingRef.current = setInterval(() => {
      i += 1
      setTyped(fullText.slice(0, i))
      if (i >= fullText.length) {
        if (typingRef.current) {
          clearInterval(typingRef.current)
          typingRef.current = null
        }
        // Fully typed → wait, then advance to next tip
        pauseRef.current = setTimeout(() => {
          setIdx((prev) => (prev + 1) % tips.length)
        }, READ_PAUSE_MS)
      }
    }, TYPE_INTERVAL_MS)

    return () => {
      if (typingRef.current) clearInterval(typingRef.current)
      if (pauseRef.current) clearTimeout(pauseRef.current)
    }
  }, [idx, tips])

  // Reset index when tips change (e.g., new data fetched)
  useEffect(() => {
    setIdx(0)
  }, [tips.length])

  if (dismissed) return null
  if (loading) return null
  if (tips.length === 0) return null

  const isFullyTyped = typed.length >= (tips[idx % tips.length] ?? '').length

  function dismiss() {
    try {
      localStorage.setItem(STORAGE_KEY, String(Date.now() + DISMISS_DURATION_MS))
    } catch {
      /* ignore */
    }
    setDismissed(true)
  }

  function cycleNow() {
    // User clicked → jump to next tip immediately (clear any active timers)
    if (typingRef.current) clearInterval(typingRef.current)
    if (pauseRef.current) clearTimeout(pauseRef.current)
    setIdx((i) => (i + 1) % tips.length)
  }

  return (
    <div className="fixed bottom-5 right-5 z-30 flex items-end gap-2 pointer-events-none">
      {/* Speech bubble */}
      <div
        className="pointer-events-auto relative bg-obsidian border border-gold/40 rounded-[5px] shadow-card px-3 py-2 min-w-[180px] max-w-[260px]"
        style={{
          boxShadow:
            '0 8px 32px rgba(90,69,39,0.18), 0 0 24px rgba(160,120,32,0.15)',
        }}
      >
        {/* Bubble tail */}
        <span
          className="absolute -right-1.5 bottom-3 w-2.5 h-2.5 rotate-45 bg-obsidian border-r border-b border-gold/40"
          aria-hidden="true"
        />
        <button
          onClick={dismiss}
          aria-label="Skryť Raulove tipy na týždeň"
          title="Skryť na týždeň — potom sa znova ozve"
          className="absolute -top-1.5 -left-1.5 w-4 h-4 rounded-full bg-stone border border-border-dim hover:border-gold-bright hover:text-crimson-bright text-text-muted font-heading text-[8px] flex items-center justify-center transition-colors"
        >
          ✕
        </button>
        <p
          onClick={cycleNow}
          className="font-body text-[10.5px] text-text-primary leading-snug cursor-pointer min-h-[2.5em]"
          title="Klikni pre ďalší tip"
        >
          {typed}
          {!isFullyTyped && (
            <span
              className="inline-block w-[1px] h-[10px] bg-gold ml-[1px] align-middle animate-pulse"
              aria-hidden="true"
            />
          )}
        </p>
        {tips.length > 1 && (
          <div className="flex items-center justify-between mt-1.5 pt-1.5 border-t border-border-dim/50">
            <span className="font-ui text-[8px] text-text-muted italic">
              {data?.period ? `· ${data.period} ·` : '·'} {idx + 1}/{tips.length}
            </span>
          </div>
        )}
      </div>

      {/* Mascot avatar */}
      <button
        onClick={cycleNow}
        className="pointer-events-auto relative shrink-0 rounded-full hover:scale-105 active:scale-95 transition-transform"
        aria-label="Raul má pre teba tip"
        title="Klikni — Raul prehodí na ďalší tip"
        style={{
          filter:
            'drop-shadow(0 0 6px rgba(160,120,32,0.45)) drop-shadow(0 3px 6px rgba(0,0,0,0.2))',
        }}
      >
        <BrandLogo className="w-12 h-12" />
        <span className="absolute -top-0.5 -right-0.5 w-2.5 h-2.5 rounded-full bg-gold-bright animate-pulse" />
      </button>
    </div>
  )
}
