import { useEffect, useRef, useState } from 'react'
import { apiFetch } from '../../utils/api'
import {
  CLIPPY_PREFS_EVENT,
  CLIPPY_SIZE_STYLES,
  getClippyPrefs,
  type ClippyPrefs,
} from '../../utils/clippyPrefs'
import { BrandLogo } from './BrandLogo'

/**
 * RaulClippy — bottom-right floating mascot (Word-Clippy vibe). Shows short,
 * witty one-liner tips generated by Raul from the latest Raul-rec input.
 *
 * Effects:
 *   - Letter-by-letter typewriter while a tip is writing itself out
 *   - 5-second pause after a tip is fully typed
 *   - Then auto-cycles to the next tip with the typewriter again
 *   - 12 tips per cycle (server-side AI generates 12, up to ~200 chars each)
 *
 * User preferences (configured in /nastavenia, stored in localStorage):
 *   - mode: 'on' | 'mascot' | 'off'
 *       on     = full widget (default)
 *       mascot = only the avatar; click reveals a single tip for ~8 s
 *       off    = nothing rendered at all
 *   - size: 'sm' | 'md' | 'lg'  (md = default, ~+20% over the old fixed size)
 *
 * Listens for the `nu:clippy-prefs-changed` event so Settings updates apply
 * instantly without reloading the page.
 *
 * Source of tips: GET /api/ai/clippy-tips (cached server-side; refreshed
 * as side-effect of POST /api/ai/recommendations, plus an auto-backfill on
 * first read if there's a Raul rec but no cached tips).
 *
 * Dismiss × silences mascot for 7 days (localStorage timestamp), independent
 * from the mode setting — that's a temporary "shut up for now" gesture.
 */

const DISMISS_KEY = 'nu_clippy_dismissed_until'
const DISMISS_DURATION_MS = 7 * 24 * 60 * 60 * 1000
const TYPE_INTERVAL_MS = 35
const READ_PAUSE_MS = 5_000
const MASCOT_BUBBLE_HOLD_MS = 8_000

interface ClippyData {
  period: string | null
  tips: string[]
}

export function RaulClippy() {
  const [prefs, setPrefs] = useState<ClippyPrefs>(() => getClippyPrefs())
  const [dismissed, setDismissed] = useState<boolean>(() => {
    try {
      const raw = localStorage.getItem(DISMISS_KEY)
      if (!raw) return false
      const until = parseInt(raw, 10)
      return Number.isFinite(until) && Date.now() < until
    } catch {
      return false
    }
  })
  const [data, setData] = useState<ClippyData | null>(null)
  const [loading, setLoading] = useState(true)
  const [idx, setIdx] = useState(0)
  const [typed, setTyped] = useState('') // currently visible text
  // In `mascot` mode the bubble pops only on click and auto-hides
  const [mascotBubbleOpen, setMascotBubbleOpen] = useState(false)

  const typingRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const pauseRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const mascotHideRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  // Reactively pick up settings changes (no reload needed).
  useEffect(() => {
    function refresh() {
      setPrefs(getClippyPrefs())
    }
    window.addEventListener(CLIPPY_PREFS_EVENT, refresh)
    return () => window.removeEventListener(CLIPPY_PREFS_EVENT, refresh)
  }, [])

  // Initial fetch — server returns latest cached tips (any month).
  useEffect(() => {
    if (dismissed || prefs.mode === 'off') return
    let alive = true
    apiFetch<ClippyData>('/api/ai/clippy-tips').then((res) => {
      if (!alive) return
      setData(res.ok ? res.data : { period: null, tips: [] })
      setLoading(false)
    })
    return () => {
      alive = false
    }
  }, [dismissed, prefs.mode])

  const tips = data?.tips ?? []

  // Typewriter cycle — only runs in full 'on' mode (no auto-rotation in mascot)
  useEffect(() => {
    if (prefs.mode !== 'on') return
    if (tips.length === 0) return
    if (typingRef.current) clearInterval(typingRef.current)
    if (pauseRef.current) clearTimeout(pauseRef.current)

    const fullText = tips[idx % tips.length] ?? ''
    setTyped('')
    let i = 0

    typingRef.current = setInterval(() => {
      i += 1
      setTyped(fullText.slice(0, i))
      if (i >= fullText.length) {
        if (typingRef.current) {
          clearInterval(typingRef.current)
          typingRef.current = null
        }
        pauseRef.current = setTimeout(() => {
          setIdx((prev) => (prev + 1) % tips.length)
        }, READ_PAUSE_MS)
      }
    }, TYPE_INTERVAL_MS)

    return () => {
      if (typingRef.current) clearInterval(typingRef.current)
      if (pauseRef.current) clearTimeout(pauseRef.current)
    }
  }, [idx, tips, prefs.mode])

  // Reset index when tips change (e.g., new data fetched)
  useEffect(() => {
    setIdx(0)
  }, [tips.length])

  // In mascot mode: auto-hide the bubble after a few seconds when shown.
  useEffect(() => {
    if (!mascotBubbleOpen) return
    if (mascotHideRef.current) clearTimeout(mascotHideRef.current)
    mascotHideRef.current = setTimeout(
      () => setMascotBubbleOpen(false),
      MASCOT_BUBBLE_HOLD_MS,
    )
    return () => {
      if (mascotHideRef.current) clearTimeout(mascotHideRef.current)
    }
  }, [mascotBubbleOpen, idx])

  // Early returns — kept after all hooks
  if (prefs.mode === 'off') return null
  if (dismissed) return null
  if (loading) return null
  if (tips.length === 0) return null

  const sizes = CLIPPY_SIZE_STYLES[prefs.size]
  const currentTip = tips[idx % tips.length] ?? ''
  const isFullyTyped = typed.length >= currentTip.length
  const showBubble = prefs.mode === 'on' || mascotBubbleOpen

  function dismissForWeek() {
    try {
      localStorage.setItem(DISMISS_KEY, String(Date.now() + DISMISS_DURATION_MS))
    } catch {
      /* ignore */
    }
    setDismissed(true)
  }

  function cycleNow() {
    if (prefs.mode === 'mascot') {
      // In mascot mode, click = pop the bubble + show the current tip immediately
      setTyped(currentTip)
      setMascotBubbleOpen(true)
      return
    }
    if (typingRef.current) clearInterval(typingRef.current)
    if (pauseRef.current) clearTimeout(pauseRef.current)
    setIdx((i) => (i + 1) % tips.length)
  }

  function cycleNext() {
    if (prefs.mode === 'mascot') {
      // Advance to next tip and re-show the bubble
      const next = (idx + 1) % tips.length
      setIdx(next)
      setTyped(tips[next])
      setMascotBubbleOpen(true)
      return
    }
    cycleNow()
  }

  return (
    <div className="fixed bottom-3 right-3 sm:bottom-5 sm:right-5 z-30 flex items-end gap-2 pointer-events-none max-w-[calc(100vw-1.5rem)]">
      {showBubble && (
        <div
          className={[
            'pointer-events-auto relative bg-obsidian border border-gold/40 rounded-[5px] shadow-card',
            sizes.bubblePadding,
            sizes.bubbleMinW,
            sizes.bubbleMaxW,
          ].join(' ')}
          style={{
            boxShadow:
              '0 8px 32px rgba(90,69,39,0.18), 0 0 24px rgba(160,120,32,0.15)',
          }}
        >
          {/* Bubble tail */}
          <span
            className="absolute -right-1.5 bottom-3 w-2.5 h-2.5 rotate-45 bg-obsidian border-r border-b border-gold/40"
            aria-hidden="true"
          />
          <button
            onClick={dismissForWeek}
            aria-label="Skryť Raulove tipy na týždeň"
            title="Skryť na týždeň — potom sa znova ozve. Trvalo vypnúť vieš v /nastavenia."
            className="absolute -top-1.5 -left-1.5 w-4 h-4 rounded-full bg-stone border border-border-dim hover:border-gold-bright hover:text-crimson-bright text-text-muted font-heading text-[8px] flex items-center justify-center transition-colors"
          >
            ✕
          </button>
          <p
            onClick={cycleNow}
            className={`font-body ${sizes.body} text-text-primary leading-snug cursor-pointer min-h-[2.5em]`}
            title="Klikni pre ďalší tip"
          >
            {typed}
            {prefs.mode === 'on' && !isFullyTyped && (
              <span
                className={`inline-block w-[1px] ${sizes.cursor} bg-gold ml-[1px] align-middle animate-pulse`}
                aria-hidden="true"
              />
            )}
          </p>
          {tips.length > 1 && (
            <div className="flex items-center justify-between mt-1.5 pt-1.5 border-t border-border-dim/50">
              <span className={`font-ui ${sizes.meta} text-text-muted italic`}>
                {data?.period ? `· ${data.period} ·` : '·'} {idx + 1}/{tips.length}
              </span>
              {prefs.mode === 'mascot' && (
                <button
                  onClick={cycleNext}
                  className={`font-heading ${sizes.meta} uppercase tracking-widest text-text-muted hover:text-gold-bright transition-colors`}
                >
                  ďalší ›
                </button>
              )}
            </div>
          )}
        </div>
      )}

      {/* Mascot avatar */}
      <button
        onClick={cycleNow}
        className="pointer-events-auto relative shrink-0 rounded-full hover:scale-105 active:scale-95 transition-transform"
        aria-label="Raul má pre teba tip"
        title={
          prefs.mode === 'mascot'
            ? 'Klikni — Raul ti ukáže tip'
            : 'Klikni — Raul prehodí na ďalší tip'
        }
        style={{
          filter:
            'drop-shadow(0 0 6px rgba(160,120,32,0.45)) drop-shadow(0 3px 6px rgba(0,0,0,0.2))',
        }}
      >
        <BrandLogo className={sizes.avatar} />
        <span
          className={`absolute -top-0.5 -right-0.5 rounded-full bg-gold-bright animate-pulse ${sizes.pulse}`}
        />
      </button>
    </div>
  )
}
